#!/bin/sh

# Base images.
# ./create base 3.12
# ./create base 3.13
# ./create base 3.14
# ./create base 3.15
# ./create base 3.16
# ./create base 3.17
./create base edge

# ./create build 3.12
# ./create build 3.13
# ./create build 3.14
# ./create build 3.15
# ./create build 3.16
./create build 3.17

# ./create gcloud 3.12
# ./create gcloud 3.13
# ./create gcloud 3.14
# ./create gcloud 3.15
./create gcloud 3.16

# Environments for a particular language.
# ./create node 3.12
# ./create node 3.13
# ./create node 3.14
# ./create node 3.15
# ./create node 3.16
./create node 3.17

# ./create node-build 3.12
# ./create node-build 3.13
# ./create node-build 3.14
# ./create node-build 3.15
# ./create node-build 3.16
./create node-build 3.17

# ./create ruby 3.12
# ./create ruby 3.13
# ./create ruby 3.14
# ./create ruby 3.15
# ./create ruby 3.16
./create ruby 3.17

# ./create ruby-build 3.12
# ./create ruby-build 3.13
# ./create ruby-build 3.14
# ./create ruby-build 3.15
# ./create ruby-build 3.16
./create ruby-build 3.17
