#!/bin/sh
set -e

name=${1}
version=${2:-latest}
img=voormedia/${name}:${version}

tput setaf 2
tput bold
echo "Building image ${img}"
tput sgr 0
docker build --platform amd64 --pull --tag ${img} --build-arg "version=${version}" ${name}

tput setaf 2
tput bold
echo "Pushing image ${img}"
tput sgr 0
docker push ${img}

tput setaf 2
tput bold
echo "Success!"
tput sgr 0
