#!/bin/bash

IMAGES=$(find . -maxdepth 1 -type d -not -name '.*' -not -name '_*' -exec basename {} \; | sort)
VERSIONS=$(wget https://alpinelinux.org/releases.json -q -O - | jq -r '(.release_branches | map(.rel_branch)) - ["edge"] | map(sub("v"; ""))[0:6][]')

echo Building images: $IMAGES
echo Building versions: $VERSIONS

IFS=$'\n'
for image in $IMAGES; do
  for version in $VERSIONS; do
    ./create "$image" "$version"
    docker image rm "voormedia/${image}:${version}"
  done
done
