#!/bin/sh
set -e
export DOCKER_BUILDKIT=1

path=${1}
name=$(echo "${path}" | cut -d '/' -f 2)
version=${2:-latest}
tag=${3}
img=voormedia/${name}:${version}

tput setaf 2
tput bold
echo "Building image ${img}"
tput sgr 0
docker build \
--cache-from ${img} \
--platform linux/amd64 \
--pull \
--tag ${img} \
--build-arg BUILDKIT_INLINE_CACHE=1 \
--build-arg "version=${version}" \
${path}

tput setaf 2
tput bold
echo "Pushing image ${img}"
tput sgr 0
docker push ${img}

if [ -n "${tag}" ]; then
  tagged=voormedia/${name}:${tag}
  tput setaf 2
  tput bold
  echo "Tagging image ${img} as ${tagged}"
  tput sgr 0
  docker tag ${img} ${tagged}
  docker push ${tagged}
fi

tput setaf 2
tput bold
echo "Success!"
tput sgr 0
