#!/bin/sh

# Base images.
./create base 3.8
./create build 3.8

./create base edge
./create build edge

# Environments for a particular language.
./create node 3.8
./create node-build 3.8
./create ruby 3.8
./create ruby-build 3.8

# Other.
./create rethinkdb 3.8
