#!/bin/sh

# Base images.
./create base 3.9
./create build 3.9

./create base edge
./create build edge

# Environments for a particular language.
./create node 3.9
./create node-build 3.9

./create node edge
./create node-build edge

./create ruby 3.9
./create ruby-build 3.9

./create ruby edge
./create ruby-build edge
