FROM alpine:edge

LABEL \
maintainer="Rolf Timmermans <rolftimmermans@voormedia.com>" \
base="alpine:edge"

# Set timezone to UTC for everything. Also see:
# https://blog.packagecloud.io/eng/2017/02/21/set-environment-variable-save-thousands-of-system-calls/
ENV \
TZ="UTC"
