FROM alpine:3.6
MAINTAINER Rolf Timmermans <rolftimmermans@voormedia.com>

# Set timezone to UTC for everything. Also see:
# https://blog.packagecloud.io/eng/2017/02/21/set-environment-variable-save-thousands-of-system-calls/
ENV \
 TZ="UTC"
